export {default as Login} from './auth/Login'
export {default as Account} from './auth/Account'
export {default as Home} from './home'
export {default as Logout} from './auth/Logout'
export {default as Register} from './auth/Register'
export {default as Watchlist} from './watchlist'
export {default as Success} from './Success'
export {default as Cart} from '../pages/cart'